version: '3.5'

services:
  nextjs-test:
    container_name: nextjs-test_latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app:ro  # Make the volume read-only to avoid conflicts
    restart: always
