version: '3.8' # Choose an appropriate version

services:
  nextjs-app:
    build: .  # Path to your Dockerfile
    ports:
      - "3000:3000"  # Map the host port to container port
    volumes:
      - .:/app # Mount your project code as a volume for development
    restart: always
